### ISSUE TITLE
china unavailable?

### ISSUE THREAD

**Issue by 13120241790** [LeonardoCardoso/Android-Link-Preview#10]
http://www.baidu.com  unavailable , your random unavailable. Network is right;

**Comment by LeonardoCardoso** [comment]
@13120241790 are you using some proxy in your network?

**Comment by 13120241790** [comment]
Thanks , Have a good . But , Some Link for less than the picture ，thumbnail。 WeChat is OK。 Do you know why is this。

**Comment by LeonardoCardoso** [comment]
@13120241790 No, when I have more available time I will test it.

**Comment by 13120241790** [comment]
No , Android App。 I am also the Android engineer。 I think your technology is very severe，Worship you。I myself under study......

**Comment by 13120241790** [comment]
Again, congratulations to your country to host the Olympics this year

**Comment by 13120241790** [comment]
String scheme = data.getScheme();
                String host = data.getHost();

My Intent scheme and host is null 。



manifest : 

` <activity
            android:name=".ui.activity.SharedReceiverActivity"
            android:screenOrientation="portrait">
            <intent-filter>
                <action android:name="android.intent.action.SEND" />

                <category android:name="android.intent.category.DEFAULT" />

                <data android:mimeType="text/plain" />
            </intent-filter>
            <intent-filter>
                <data
                    android:host="*"
                    android:scheme="http" />
                <data
                    android:host="*"
                    android:scheme="https" />

                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>`


Why is this？ Trouble you

**Comment by 13120241790** [comment]
String scheme = data.getScheme();
                String host = data.getHost();

My Intent scheme and host is null 。



manifest : 

` <activity
            android:name=".ui.activity.SharedReceiverActivity"
            android:screenOrientation="portrait">
            <intent-filter>
                <action android:name="android.intent.action.SEND" />

                <category android:name="android.intent.category.DEFAULT" />

                <data android:mimeType="text/plain" />
            </intent-filter>
            <intent-filter>
                <data
                    android:host="*"
                    android:scheme="http" />
                <data
                    android:host="*"
                    android:scheme="https" />

                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
            </intent-filter>`


Why is this？ Trouble you
