### ISSUE TITLE
Uncancelable AsyncTask

### ISSUE THREAD

**Issue by theGnartist** [LeonardoCardoso/Android-Link-Preview#17]
I have a fix for this and will gladly submit a PR if you're interested in incorporating it into your library.  

The current implementation doesn't allow for cancelling of the asynctask.  This causes unexpected behavior when used in a RecyclerView as the task may complete after the ViewHolder has been rebound to a different element.   It also is a potential cause of crashes if the task completes after the Activity has been destroyed (during screen orientation change, backgrounding the app, or simply dismissing the activity to navigate to another screen in the app).

My change would add a cancel() method to the public API of the TextCrawler as well as cancellation handling inside the for loops of the async tasks.

**Comment by theGnartist** [comment]
https://github.com/LeonardoCardoso/Android-Link-Preview/pull/18

**Comment by LeonardoCardoso** [comment]
Thanks, @theGnartist . Merged!

**Comment by RuchaBhattJoshi** [comment]
@aleedy  how to use it?
