### ISSUE TITLE
Setup in eclipse! 

### ISSUE THREAD

**Issue by demo-Ashif** [LeonardoCardoso/Android-Link-Preview#3]
For some unavoidable reason I can't move my main project in Android Studio. And I have to use this library. So how will I setup this library in Eclipse?  Please help me out

**Comment by LeonardoCardoso** [comment]
Sorry, but Eclipse lost its support for Android a while ago. I ask you to consider using Android Studio. It's better! And you can use this library with gradle. Even more beautiful!

https://github.com/LeonardoCardoso/Android-Link-Preview#how-to-use-with-gradle
