### ISSUE TITLE
Opening of wrong link

### ISSUE THREAD

**Issue by asifali22** [LeonardoCardoso/Android-Link-Preview#9]
I added a post, then clicked on it. Redirected to browser with the respective link. Then I added another post with different link using random, now when I click on this new post it opens in browser with its link,  but now when clicked on previous post it still redirects to the recently added post rather the link of previous post.

**Comment by LeonardoCardoso** [comment]
@asifali22 I'll check it asap.

**Comment by asifali22** [comment]
Sure, I'm busy these days , if not fixed by next month I'll definitely try to contribute by fixing small bug.

**Comment by srujan7** [comment]
@asifali22 even i found this issue on the demo app but i dont know if its a bug in app or library! Did you implement this lib already? Did you face the issue?

**Comment by srujan7** [comment]
Just solved it.. Here goes my first github full request. LOL

**Comment by gregijc** [comment]
@srujan7 how do you solved it sir? can you explain the logic, or even maybe the code. hehe.

**Comment by LeonardoCardoso** [comment]
@gregijc It's been merged to the master branch.

**Comment by srujan7** [comment]
@gregijc  Sure! would you like to try it your self? i'll give you a hint. 
There is only one src file in java dir. Open it and go to line 202 (If I remember it well). There is an onClickListener. Put a "Toast" inside that method and run the code. See we you get the toast. Click on the various links and again check the toast. Pretty simple. 

( p.s. do not call me sir! I'm your age :D )

**Comment by gregijc** [comment]
@LeonardoCardoso how can i get the master branch? i am already using these two:
    compile 'org.jsoup:jsoup:1.8.3' // required
    compile 'com.leocardz:link-preview:1.2.1@aar'

@srujan7 how do i open file in java dir? i am using android studio..

i'm sorry if i asked some obvious question. i only learned mobile from udacity,and still new in mobile.
thank you before.

**Comment by srujan7** [comment]
No problem
Here is the fine I told you about: https://github.com/LeonardoCardoso/Android-Link-Preview/blob/master/app/src/main/java/com/leocardz/link/preview/Main.java

You can find this file **under** java dir once you open the project in studio. 

Happy learning

**Comment by LeonardoCardoso** [comment]
@gregijc Yes, it's on the main branch, but I didn't create a new version yet. I'll do it tonight!

**Comment by gregijc** [comment]
@srujan7 i see, thank you so much.

@LeonardoCardoso okay thanks. i'll be waiting for the update. thank you so much once again.

**Comment by srujan7** [comment]
@LeonardoCardoso  Ah please cross check the compiled code when you create the new version. I had no time to create a repo and push the changes so I edited the code in the github editor. Just in case I did a typo.

**Comment by LeonardoCardoso** [comment]
@srujan7 ok
@gregijc ok

**Comment by LeonardoCardoso** [comment]
Done!

**Comment by RuchaBhattJoshi** [comment]
@LeonardoCardoso  hello i'm using this library recently and i got this issue again. i'm using in chat like whatsapp so when i sent one link it works perfect, when i sent second link then first link also shows preview of second link, i'm not quite sure about if its library or my logic but i find this issue and its already exist here so i thought it might be library. i'm trying to solve this if i will able to do it i'll update here but in case if you can check this issue it will be helpful. thank you.
